name = "accounting-service"
main = "src/index.ts"
compatibility_date = "2024-11-19"

[dev]
port = 8794

[[d1_databases]]
binding = "DB"
database_name = "accounting-db"
database_id = "41e11ea2-9abb-438d-8d7c-6d441e5a8f11"
migrations_dir = "migrations"

[[queues.producers]]
binding = "ACCOUNTING_EVENTS_QUEUE"
queue = "accounting-events"

[vars]
ENVIRONMENT = "development"
